### ISSUE TITLE
Cannot pull soplex branch

### ISSUE THREAD

**Issue by Specy** [scipopt/soplex-sys#2]
Hello! i am having errors compiling the library for target `wasm32-unknown-unknown` and was trying to figure out what could be wrong but i cannot pull the repository as it fails to find the branch https://github.com/scipopt/soplex/tree/8b4e254607386e93d8df0420194ca42154588f59

**Comment by mmghannam** [comment]
Sorry my bad! it should be working now

**Comment by mmghannam** [comment]
I just tried compiling for the wasm target, and the cmake crate (that soplex-sys uses) apparently doesn't support this target.

**Comment by Specy** [comment]
It *might* be possible [see here](https://github.com/rafaelbeckel/test-c-rust-wasm/tree/master/crates/5_rust_bindgen) and [here](https://github.com/rafaelbeckel/test-c-rust-wasm/pull/1), that's what I wanted to experiment with.

Will surely be a huge headache but it's worth a shot

**Comment by mmghannam** [comment]
I managed to get target `wasm32-unknown-emscripten` to build without errors. Not sure if this also works for you but probably worth a try :)

**Comment by mmghannam** [comment]
If the original problem is resolved (with the branch) please close this issue.

**Comment by Specy** [comment]
yep just checked and works! 

Should i open an issue in `soplex-rs` about the wasm target?

**Comment by mmghannam** [comment]
it probably fits in `soplex-sys` more since it's related to how soplex is compiled/bundled.
